name: Android CI
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Build & Lint
        run: ./gradlew clean lint assembleDebug --no-daemon --stacktrace
